### ISSUE TITLE
When user create a city, validate the latitude and longitude to be within range

### ISSUE THREAD

**Issue by iamfranco** [vkammili5/weather-api#13]
When user send a **POST** request to `/city`, use some validation to ensure that the `latitude` and `longitude` are within range, such that:

$$-90\degree \leq \textrm{latitude} \leq 90\degree$$

$$-180\degree \leq \textrm{longitude} \leq 179.8\degree$$

Note: the public **API open-meteo forecast** has a quirk that if we send longitude of say 179.9 it'll respond with status code `502 Bad Gateway`, so it's best to restrict the longitude to be at most $179.8 \degree$

If the user sends **POST** request with latitude longitude outside of those ranges, then our API should respond with status code `400 Bad Request`.

**Comment by vkammili5** [comment]
Resolved Issue.
