### ISSUE TITLE
weather model's WeatherCode is shown as integer in json because it is an enum, we want it to be string instead

### ISSUE THREAD

**Issue by iamfranco** [vkammili5/weather-api#14]
Currently, if user sends a **GET** request to `api/v1/weather/{cityName}` endpoint, the API will respond with something like 

```json
{
  "latitude": 52.52,
  "longitude": 13.419998,
  "weatherCode": 1,
  "whatToPrepare": "bring coat"
}
```

where the `"weatherCode"` is `1`, rather than `"ClearSky"`.

It would be much better to have the json object contain the string `"ClearSky"` for `"weatherCode"` so that it is easily readable for the user.

To achieve this, we probably need to add some attribute above the `WeatherCode` property in `Weather` class:

```c#
public class Weather
{
  // ...

  [JsonConverter(typeof(JsonStringEnumConverter))] 
  public WeatherCode WeatherCode { get; set; }
  
  // ...
}
```

**Comment by namita1409** [comment]
Issue resolved
